apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-demo
  namespace: investigation-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-demo
  template:
    metadata:
      labels:
        app: config-demo
    spec:
      containers:
        - name: app
          image: config-demo:local
          imagePullPolicy: Never
          env:
            - name: INVENTORY_SERVICE_URL
              value: http://inventory-api:8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
